name: Changes to the changelog
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  happened:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Check for logged changes
        run: git diff --name-only ${{ github.event.pull_request.base.sha }}..${{ github.sha }} | grep ^CHANGELOG.md$
